### ISSUE TITLE
Can this be used in real-time?

### ISSUE THREAD

**Issue by icheered** [spotify/basic-pitch-ts#12]

**Comment by sudomf** [comment]
It would be very very useful

**Comment by drubinstein** [comment]
Hi. The short answer is not without a major change to the step after inference. This has come up in the basic-pitch issues pages as well. You can read more about why it is not currently possible [here](https://github.com/spotify/basic-pitch/issues/19).

**Comment by icheered** [comment]
@sudomf my use case was pitch detection in pianos and I ended up using webmidi (I did have to buy an adapter from midi to usb). Depending on your usecase this might be something you can look in to.

**Comment by sudomf** [comment]
@icheered My use case is for guitar. So, a little bit complicated.
